---
framework: mocha
licenseTier: xsmall
postMerge: 
  pattern: 
    - "./test/**/*.spec.tts"
preMerge:
  pattern:
    - "./test/**/*.spec.ts"
preRun:
     command:
        - npm i
postRun:
     command:
        - node --version
version: 2.0
